name: disco-rip
version: 0.1.0.0
github: "dpwiz/disco-rip"
license: BSD-3-Clause
author: "IC Rainbow"
maintainer: "aenor.realm@gmail.com"
copyright: "2026 IC Rainbow"

extra-source-files:
- README.md
- CHANGELOG.md

synopsis: Discord RPC client, mostly for RichPresence
category: Web

dependencies:
- aeson
- async
- base >= 4.7 && < 5
- binary
- bytestring
- containers
- directory
- filepath
- network
- random
- stm
- text
- uuid

when:
- condition: os(windows)
  dependencies:
  - Win32
- condition: "!os(windows)"
  dependencies:
  - unix

library:
  source-dirs: src

language: GHC2021
default-extensions:
- ApplicativeDo
- BlockArguments
- DeriveAnyClass
- DeriveGeneric
- DerivingStrategies
- DerivingVia
- ImportQualifiedPost
- LambdaCase
- NamedFieldPuns
- NoFieldSelectors
- OverloadedStrings
- RecordWildCards
- StrictData

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

tests:
  disco-rip-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
    - disco-rip
    - tasty
    - tasty-hunit
